[workspace]
# Git settings
git_release_enable = true
git_tag_enable = true
git_tag_name = "{{ package }}-v{{ version }}"

# Changelog settings
changelog_update = true
changelog_path = "CHANGELOG.md"

# Release settings
release_always = false
allow_dirty = false

[[package]]
name = "tokio_implementations"
publish = false
release = false
