[package]
name = "tokio_pub_sub"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
log = "0.4.26"
tokio = { version = "1.44.0", features = ["full"] }
tokio_pub_sub_macros = { path = "../tokio_pub_sub_macros" }

[dev-dependencies]
test-log = "0.2.17"
