[package]
name = "async_pub_sub"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
log = "0.4.26"
tokio = { version = "1.44.0", features = ["full"] }
async_pub_sub_macros = { path = "../async_pub_sub_macros" }

[dev-dependencies]
env_logger = "0.11.7"
rand = "0.9.0"
test-log = "0.2.17"
tokio_implementations = { path = "../tokio_implementations" }
