[package]
name = "tokio_implementations"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.44.1", features = ["full"] }
async_pub_sub = { path = "../async_pub_sub" }
